#!/usr/bin/env bash
mode=$1

STEP=5
RAISE_VOLUME="pamixer -i $STEP"
LOWER_VOLUME="pamixer -d $STEP"
TOGGLE_VOLUME="pamixer -t"

volumeId=$(cat /home/filo/.scripts/dunstids/volume)
appName="Volume Control"
defaults="-u low -r $volumeId"

case $mode in
    "raise")
        eval "$RAISE_VOLUME"
        ;;
    "lower")
        eval "$LOWER_VOLUME"
        ;;
    "toggle")
        eval "$TOGGLE_VOLUME"
        ;;
    *)
        echo "Usage: $0 <raise|lower|toggle>"
esac


volume=$(pamixer --get-volume)
volumeHuman=$(pamixer --get-volume-human)

if [[ $volumeHuman == "muted" ]]; then
    icon=audio-volume-muted
elif (( ${volumeHuman:0:-1} > 80 )); then
    icon=audio-volume-high
elif (( ${volumeHuman:0:-1} > 30 )); then
    icon=audio-volume-medium
else 
    icon=audio-volume-low
fi

#icon=~/880950.svg

summary="Volume: $volume"
#body="$(getProgressString 10 '<b></b>' '' $volume)"
body="$(getProgressString 20 '<b>■</b>' ' ' $volume)"
dunstify -a "Volume Control" $defaults -i $icon \
    "$summary" "$body" \
    -t 1000
