#!/bin/node

const exec = require('child_process').exec;
const myExec = (cmd) => {
  return new Promise((resolve, reject) => {
    exec(cmd, (error, stdout, stderr) => {
      if (error || stderr) return reject(error);
      resolve(stdout);
    });
  });
}
  
//myExec('firefox')
  //.then((stdout) => {
    //console.log(stdout);
  //})
  //.catch(() => {
    //console.log('fallito');
  //})

const args = process.argv.slice(2);

const pikaliticize = (pokemon, format) =>
  '\'https://www.pikalytics.com/pokedex/' + format + '/' + pokemon + '\'';

if (args.length > 0) {
  const list = args.reduce((acc, arg) => acc += ' ' + arg);
  const pokemons = list.split('/');
  console.log(pokemons);
  const links = pokemons
    .map((pokemon) => pikaliticize(pokemon.trim(), 'vgc2018'))
    .reduce((acc, link) => acc += ' ' + link);

  myExec('firefox ' + links)
  .then((stdout) => {
    console.log('Ok.');
  })
  .catch((error) => {
    console.log('Error');
  });

} else {
  console.log('Usage: node pykalitics <team>');
}
