#!/usr/bin/env bash

CURRENT_LAYOUT_COMMAND="setxkbmap -query | grep layout | awk '{print "'$2'"}'"
MY_LAYOUTS="it us"

xkbId=$(cat /home/filo/.scripts/dunstids/xkb)
current_layout=$(eval "$CURRENT_LAYOUT_COMMAND")
target_layout=$(echo "$MY_LAYOUTS" | sed -e s/$current_layout// | xargs)
opts="-u low -r $xkbId"

echo $current_layout
echo $target_layout

case $target_layout in
    "it")
        icon="indicator-keyboard-It"
        ;;
    "us")
        icon="indicator-keyboard-En"
        ;;
esac
# xargs does the trimming

setxkbmap $target_layout
dunstify -a "Keyboard Layout" $opts "Change keyboard layout" "$target_layout" -t 1000 \
    -i $icon
#dunstify -a "Volume Control" $defaults -i $icon \
    #"$summary" "$body" \
    #-t 2000
